### ISSUE TITLE
How to use it in Automatic?

### ISSUE THREAD

**Issue by Deathawaits4** [philz1337x/clarity-upscaler#10]
Hei i really tried understanding your readme.. but i really dont get how to use it in Automatic. Just copy pasting the params doesnt work. It only applies the cfg, denoising and so on. But what about the rest? I tried going through the params one by one but i have no idea which control net to use or how to even select the correct upscaler

**Comment by rrmdp** [comment]
You need to paste the params into the main prompt field and click on the little blue arrow icon (underneath Generate)

**Comment by wangwenqiao666** [comment]
> You need to paste the params into the main prompt field and click on the little blue arrow icon (underneath Generate)
![Uploading image.png…]()
It didn't work at all

**Comment by fantomac** [comment]
Params don't go to the right place, I have to put it manually....
Not sure if It must be used in text 2 img or img 2 img... trying both...

**Comment by philz1337x** [comment]
Does anybody know how to input the params automatically?

**Comment by philz1337x** [comment]
> Params don't go to the right place, I have to put it manually.... Not sure if It must be used in text 2 img or img 2 img... trying both...

img2img
