### ISSUE TITLE
What are the right steps to use these parameters on sd webui?

### ISSUE THREAD

**Issue by gin063** [philz1337x/clarity-upscaler#12]
I think something went wrong in one of the steps, I found that the effect is very different from your demonstration.
prompt:
masterpiece, best quality, highres, <lora:more_details:0.5> <lora:SDXLrender_v2.0:1>
Negative prompt: (worst quality, low quality, normal quality:2) JuggernautNegative-neg
Steps: 18, Sampler: DPM++ 3M SDE Karras, CFG scale: 6, Seed: 1337, Size: 792x1000, Model hash: 338b85bc4f, Model: juggernaut_reborn, Denoising strength: 0.35, Tiled Diffusion upscaler: 4xUltrasharp_4xUltrasharpV10, Tiled Diffusion scale factor: 2, ControlNet 0: "Module: tile_resample, Model: control_v11f1e_sd15_tile [a371b31b], Weight: 0.6, Resize Mode: 1, Low Vram: False, Processor Res: 512, Threshold A: 1, Threshold B: 1, Guidance Start: 0, Guidance End: 1, Pixel Perfect: True, Control Mode: 1, Hr Option: HiResFixOption.BOTH, Save Detected Map: True", Lora hashes: "more_details: 3b8aa1d351ef, SDXLrender_v2.0: 3925cf4759af", Version: v1.8.0

<img width="1250" alt="image" src="https://github.com/philz1337x/clarity-upscaler/assets/64243335/20063424-0f6c-415e-b965-4015c14af359">
<img width="631" alt="image" src="https://github.com/philz1337x/clarity-upscaler/assets/64243335/00fa457b-2d4f-411b-a730-ecf0c4339dba">
<img width="635" alt="image" src="https://github.com/philz1337x/clarity-upscaler/assets/64243335/1fdb352a-fb37-40b6-95c9-1ee5524fc9a5">

model: juggernaut_reborn
loras: more_details, SDXLrender
embeddings: JuggernautNegative-neg
extensions:
Tiled Diffusion
controlnet model: control_v11f1e_sd15_tile

**Comment by gin063** [comment]
It looks like my generated data is different from yours: 
1. I don't have the following in my data: 
{"Method": "MultiDiffusion", "Tile tile width": 112, "Tile tile height": 144, "Tile Overlap": 4, "Tile batch size": 8, "Upscaler": "4x-UltraSharp", "Upscale factor": 2, "Keep input size": true}
2. Save Detected Map: False", mine is "true".

**Comment by rainsoulsrx** [comment]
> Hr Option: HiResFixOption.BOTH,
Hi, where can I set this this param in webui?
