### ISSUE TITLE
Could you please add dev.py just like you did here- https://github.com/philz1337x/style-transfer/blob/main/dev.py

### ISSUE THREAD

**Issue by anujsinha72094** [philz1337x/clarity-upscaler#13]
We need this in order to understand the exact code @philz1337x  . Thanks

**Comment by philz1337x** [comment]
In Style-transfer I was able to add a simple dev file because the code is using diffusers. 

In this repo I am using webui a1111 in cog, so the simple dev file in this case would be the a1111 code.
