### ISSUE TITLE
Bug report on clarity over replicate

### ISSUE THREAD

**Issue by cranavis** [philz1337x/clarity-upscaler#15]
Hi.

For clarity on replicate.

When I use a large image, I have rainbow lines at the border of the tiles. Every time.
Easy to reveal by adding a little brightness.
Unusable result.
I noticed this after doing 3 photo edits...
See cut example:
https://ibb.co/ccxFmvQ

Have a nice day.
Cranavis

**Comment by philz1337x** [comment]
Hi Cranavis,

Could you please share your replicate prediction link?

We could solve this with a higher tile overlapping.

**Comment by cranavis** [comment]
An exemple : 
https://replicate.com/philz1337x/clarity-upscaler?prediction=trwtfbv5qxrgg0cen8tvmn7qs8
add luminosity to check rainbow.
Say me if you need more example.

But this is for each tiled image. (I suppose this is tiles problem)

But each time on large image.


I am a photographer. I'm looking for an enhancer to remaster my photos. For art photography like mine, in the dark, your AI is much better than magnific. Less destructive. And much cheaper on repliacte since I don't upscale. I'm still at scale 1 to remaster. My entire raw photos are in 5000x4000 before going to 20000x140000 with topaz. For certain objects I sometimes have images in 12000x1000.



The problem is not the size of the tiles, but their management.

So, until this is resolved, it is impossible for me to use your software for large images, or large parts of images.

Have nice days.
Yann

De : philz1337x ***@***.***>
À : philz1337x/clarity-upscaler ***@***.***>
Sujet : Re: [philz1337x/clarity-upscaler] Bug report on clarity over replicate (Issue #15)
Date : 05/04/2024 04:52:31 Europe/Paris
Copie à : cranavis ***@***.***>;
   Author ***@***.***>


Hi Cranavis,

Could you please share your replicate prediction link?

We could solve this with a higher tile overlapping.

**Comment by philz1337x** [comment]
I can't open your prediction link, you need to click the share button in replicate to create a public link.

**Comment by cranavis** [comment]
https://replicate.com/p/mypk11y3g9rgp0ces1dtq44ww4 
The shared link
Remember to up exposition, to see vertical lines.

Have nice days
yann



De : philz1337x ***@***.***>
À : philz1337x/clarity-upscaler ***@***.***>
Sujet : Re: [philz1337x/clarity-upscaler] Bug report on clarity over replicate (Issue #15)
Date : 09/04/2024 07:27:12 Europe/Paris
Copie à : cranavis ***@***.***>;
   Author ***@***.***>


I can't open your prediction link, you need to click the share button in replicate to create a public link.

**Comment by cranavis** [comment]
here is an other link where we can easly see the seprarton.
https://replicate.com/p/bjd45py429rgj0cev2w98y0kh0 
That a pain. 
Replica is the only one good i find for photos.
Better than Magnific, better than firefly.
Because using low parameters, no heavy transform, not destructive.
Just this line is destrictive.

I join exemple i did. 
Without clarity (1c ; 2c) - with clarity 1d ; 2c)
That is web size. Real size is average 20.000 x 14.000 pixels
I didn't search add details. I search avec perfect result.
Details are not ever good for best result.
Smooth of the 2c is perfect.

Except this line, it's a pleasure to use Clarity.
Have a nice day.
Yann




De : philz1337x ***@***.***>
À : philz1337x/clarity-upscaler ***@***.***>
Sujet : Re: [philz1337x/clarity-upscaler] Bug report on clarity over replicate (Issue #15)
Date : 09/04/2024 07:27:12 Europe/Paris
Copie à : cranavis ***@***.***>;
   Author ***@***.***>


I can't open your prediction link, you need to click the share button in replicate to create a public link.

**Comment by cranavis** [comment]
Hi.

Please let us use lora file from local path.
From our computer.
Too many link are not direct link to the file.
Unsable from clarity.

Have nice days.


De : philz1337x ***@***.***>
À : philz1337x/clarity-upscaler ***@***.***>
Sujet : Re: [philz1337x/clarity-upscaler] Bug report on clarity over replicate (Issue #15)
Date : 09/04/2024 07:27:12 Europe/Paris
Copie à : cranavis ***@***.***>;
   Author ***@***.***>


I can't open your prediction link, you need to click the share button in replicate to create a public link.

**Comment by philz1337x** [comment]
yes but replicate wants an url while using the api.

**Comment by cranavis** [comment]
Maybe a 1 hour temporary folder when we can upload file we have in local, and get a direct link tu use it.




De : philz1337x ***@***.***>
À : philz1337x/clarity-upscaler ***@***.***>
Sujet : Re: [philz1337x/clarity-upscaler] Bug report on clarity over replicate (Issue #15)
Date : 22/04/2024 20:12:50 Europe/Paris
Copie à : cranavis ***@***.***>;
   Author ***@***.***>


yes but replicate wants an url while using the api.
