### ISSUE TITLE
ValueError: 'tiled diffusion' is not in list

### ISSUE THREAD

**Issue by 823863429** [philz1337x/clarity-upscaler#16]
thank you for your great work
I got an error when running predict.py：
Try to disable xformers, but it is not enabled. Skipping...
Style database not found: /content/clarity-upscaler/styles.csv
Loading weights [None] from /content/clarity-upscaler/models/Stable-diffusion/epicrealism_naturalSinRC1VAE.safetensors
Creating model from config: /content/clarity-upscaler/configs/v1-inference.yaml
fatal: No names found, cannot describe anything.
====>scripts:[<img2imgalt.py.Script object at 0x7d4488a486d0>, <loopback.py.Script object at 0x7d4488a48a30>, <outpainting_mk_2.py.Script object at 0x7d4488a48a60>, <poor_mans_outpainting.py.Script object at 0x7d4488a48ac0>, <prompt_matrix.py.Script object at 0x7d4488a48b20>, <prompts_from_file.py.Script object at 0x7d4488a48b50>, <sd_upscale.py.Script object at 0x7d4488a49240>, <xyz_grid.py.Script object at 0x7d4488a492a0>, <extra_options_section.py.ExtraOptionsSection object at 0x7d4488a492d0>, <hypertile_script.py.ScriptHypertile object at 0x7d4488a49300>, <refiner.py.ScriptRefiner object at 0x7d4488a49330>, <seed.py.ScriptSeed object at 0x7d4488a49360>]
Traceback (most recent call last):
  File "/content/clarity-upscaler/modules/api/api.py", line 41, in script_name_to_index
    return [script.title().lower() for script in scripts].index(name.lower())
ValueError: 'tiled diffusion' is not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/clarity-upscaler/predict.py", line 331, in <module>
    predictor.setup()
  File "/content/clarity-upscaler/predict.py", line 127, in setup
    self.api.img2imgapi(req)
  File "/content/clarity-upscaler/modules/api/api.py", line 426, in img2imgapi
    script_args = self.init_script_args(img2imgreq, self.default_script_arg_img2img, selectable_scripts, selectable_script_idx, script_runner)
  File "/content/clarity-upscaler/modules/api/api.py", line 331, in init_script_args
    alwayson_script = self.get_script(alwayson_script_name, script_runner)
  File "/content/clarity-upscaler/modules/api/api.py", line 298, in get_script
    script_idx = script_name_to_index(script_name, script_runner.scripts)
  File "/content/clarity-upscaler/modules/api/api.py", line 43, in script_name_to_index
    raise HTTPException(status_code=422, detail=f"Script '{name}' not found") from e
fastapi.exceptions.HTTPException
Loading VAE weights from commandline argument: models/VAE/vae-ft-mse-840000-ema-pruned.safetensors
Applying attention optimization: xformers... done.
Model loaded in 3.9s (load weights from disk: 0.9s, create model: 1.2s, apply weights to model: 1.0s, load VAE: 0.2s, calculate empty prompt: 0.4s).

**Comment by philz1337x** [comment]
seems like you need to install multi-diffusion extension

**Comment by 823863429** [comment]
> seems like you need to install multi-diffusion extension

how to install multi-diffusion extension？I don't seem to see it in your requirements.txt

**Comment by datnt-hgmeida** [comment]
@823863429 @philz1337x Do you have any suggestion for fix this ?

**Comment by e-cal** [comment]
You need to clone the [multidiffusion upscaler](https://github.com/pkuliyi2015/multidiffusion-upscaler-for-automatic1111) and [controlnet](https://github.com/Mikubill/sd-webui-controlnet/tree/1.1.436) extensions to `extensions/`. 

For the controlnet extension, the most recent version does not work with this repo, so clone tag [1.1.436](https://github.com/Mikubill/sd-webui-controlnet/releases/tag/1.1.436):
`git clone --depth 1 --branch 1.1.436 git@github.com:Mikubill/sd-webui-controlnet.git`

**Comment by philz1337x** [comment]
@e-cal added a great download-weights.py file to make all this easier!
