### ISSUE TITLE
can you port your workflow to run inside comfyUI and make some nodes to explore

### ISSUE THREAD

**Issue by jags111** [philz1337x/clarity-upscaler#24]
it will be very nice to have this run inside comfyUI and check same .. let me know if that is possible to port it. Thanks

**Comment by Smuzzies** [comment]
I'd like to second that motion, results are stunning. ComfyUI noodles would be wonderful.

**Comment by philz1337x** [comment]
I tried to reproduce my workflow in comfyui but wasn't able.

But I created an API node for it: https://github.com/philz1337x/clarity-upscaler#-comfyui
