### ISSUE TITLE
 achieve the same effect in comfyui?

### ISSUE THREAD

**Issue by yiniesta** [philz1337x/clarity-upscaler#25]
Are there any plans to achieve the same effect in the comfyui?
this will be very helpful for comfyui users. hope to consider.

**Comment by philz1337x** [comment]
I have built an api node for ComfyUI, see here: https://github.com/philz1337x/clarity-upscaler#-comfyui

**Comment by czzerone** [comment]
> I have built an api node for ComfyUI, see here: https://github.com/philz1337x/clarity-upscaler#-comfyui

hi, thanks for your work!! i download your node in comfyui, but when I run with it, I got a error like this:
<img width="756" alt="image" src="https://github.com/philz1337x/clarity-upscaler/assets/38934182/bbd925c7-5eab-4cab-998c-8952e846ccc0">

I replace the 'api_key' in the 'api_key_override' of the node

**Comment by roblaughter** [comment]
If you want to do this natively in Comfy using your own compute, I put together a workflow with the same basic process and a few enhancements. Give it a try [here](https://github.com/roblaughter/comfyui-workflows/blob/main/ClarityUpscaleSD15.json).
