### ISSUE TITLE
Full list of extensions and weights with their versions

### ISSUE THREAD

**Issue by vnovak1** [philz1337x/clarity-upscaler#26]
Hello,
great work you've done here! I wanted to try it out myself locally, but I'm having problems running this model using cog. More specifically, I'm getting `RuntimeError: The size of tensor a (70) must match the size of tensor b (64) at non-singleton dimension 3` error when I try to run it on the example bird image with all settings unset (default). 
I believe the problem can be happening because I got the wrong versions of some extension or weights downloaded. Could you please, or someone else who has managed to make it work provide full list of dependencies with the versions one has to manually download? 

Any help is appreciated! Thank you and have a great day!

**Comment by shengming-yin** [comment]
Hello，
Have you found the right version for ControlNet extension, I met the same question.
Thanks~

**Comment by e-cal** [comment]
For the controlnet extension, the most recent version does not work with this repo, so clone tag [1.1.436](https://github.com/Mikubill/sd-webui-controlnet/releases/tag/1.1.436):
`git clone --depth 1 --branch 1.1.436 git@github.com:Mikubill/sd-webui-controlnet.git`

**Comment by philz1337x** [comment]
@e-cal added a great download-weights.py file to make all this easier!
