### ISSUE TITLE
error when using clarity ai with cog

### ISSUE THREAD

**Issue by SAKSoomro** [philz1337x/clarity-upscaler#30]
I downloaded all 3 models and put into models directory
Kindly explain the error, 

Starting Docker image cog-clarity-upscaler-base and running setup()...
Traceback (most recent call last):
File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cog/server/worker.py", line 189, in _setup
run_setup(self._predictor)
File "/root/.pyenv/versions/3.10.4/lib/python3.10/site-packages/cog/predictor.py", line 84, in run_setup
predictor.setup()
File "/src/predict.py", line 33, in setup
initialize.imports()
File "/src/modules/initialize.py", line 24, in imports
from modules import paths, timer, import_hook, errors  # noqa: F401
File "/src/modules/paths.py", line 34, in <module>
assert sd_path is not None, f"Couldn't find Stable Diffusion in any of: {possible_sd_paths}"
AssertionError: Couldn't find Stable Diffusion in any of: ['/src/repositories/stable-diffusion-stability-ai', '.', '/']
ⅹ Model setup failed

**Comment by datnt-hgmeida** [comment]
you run `python download_weights.py` to fix this

**Comment by e-cal** [comment]
also need to add the vae to `download_weights.py`

```python
# VAE
download_file(
    "https://huggingface.co/stabilityai/sd-vae-ft-mse-original/resolve/main/vae-ft-mse-840000-ema-pruned.safetensors?download=true",
    "models/VAE",
    "vae-ft-mse-840000-ema-pruned.safetensors"
)
```

**Comment by philz1337x** [comment]
@e-cal added a great download-weights.py file to make all this easier!
