### ISSUE TITLE
API does not work, getting Timeout error

### ISSUE THREAD

**Issue by yeyintthu9** [philz1337x/clarity-upscaler#37]
Hi @philz1337x,
I am currently using this upscaler API with comfyUI plugin and getting the following API timeout error.
Is the service running properly ? 
![image](https://github.com/philz1337x/clarity-upscaler/assets/33410354/1e7ee694-2bc4-4085-9b3b-0ea4b076c071)

**Comment by philz1337x** [comment]
How big is your output image?
I think you can't go further than ~36 Megapixels bc otherwise it will take to long and timeout.

**Comment by yeyintthu9** [comment]
523x523 with upscaling factor 16, when I reduced the upscaling factor to 4. It is successful.
