### ISSUE TITLE
lol, i think this philz guy is trolling us, nothing works as intendet, beside of api version, where he get money

### ISSUE THREAD

**Issue by NeverBeLazyG** [philz1337x/clarity-upscaler#51]
i think he made the scripts and readme intentionally chaotic, so no one can reproduce it locally.

he wants you to use the api or the paid version.

very clever guy 🤣

**Comment by philz1337x** [comment]
This is not true.

I even show multiple ways to use Clarity-Upscaler for free, for example, with a free workflow in ComfyUI or with A1111. The way of doing it through Cog is more complex, which is because of the nature of Cog.

Let me know your issue, and I am happy to assist.

**Comment by NeverBeLazyG** [comment]
bro sorry i dont believe. you. i am in that ai upscaling and ai generation game since years, i installed like hundrets of models, workflows, compfy ui, forge, a1111, i got really everything to run. there is only one which i was not able to get run corretly, and thats yours. i think you make it intentionally, to sell your api things. its really pathetic. you take models from others, bake something new, and then trick around not to share the information.

**Comment by philz1337x** [comment]
you: "you dont give information"

the information I gave:

> How to Upscale Images for Free with Clarity Upscaler:

1. Install A1111 WebUI (three options from hardest to easiest):
a) Follow the official tutorial: [https://github.com/AUTOMATIC1111/stable-diffusion-webui#installation-and-running](https://t.co/BPkc6bxYni)
b) Watch the YouTube tutorial: [https://youtube.com/watch?v=kqXpAKVQDNU](https://t.co/EhYZ2qnuPa)
c) Use One-Click start on 
[@runpod_io](https://x.com/runpod_io)
:  [https://rundiffusion.com](https://t.co/79mrqzKybV) ($0.5/h)

2. Install the extension:
Open A1111 WebUl -> Click Tab "Extensions" -> Click Tab "Available" -> Find "[Tiled Diffusion with Tiled
VAE]" -> Click Install

3. Download the models and place them in the correct folder:
- [https://huggingface.co/dantea1118/juggernaut_reborn/resolve/main/juggernaut_reborn.safetensors?download=true](https://t.co/GblF3ZQI1G) -> stable-diffusion-webui/models/Stable-diffusion
- [https://huggingface.co/philz1337x/upscaler/resolve/main/4x-UltraSharp.pth?download=true](https://t.co/sFDClKrEaN) -> models/ESRGAN
- [https://huggingface.co/philz1337x/embeddings/resolve/main/JuggernautNegative-neg.pt?download=true](https://t.co/DSDmb35hQG) -> embeddings
- [https://huggingface.co/philz1337x/loras/resolve/main/SDXLrender_v2.0.safetensors?download=true](https://t.co/7fLWBFVkul) -> models/Lora
- [https://huggingface.co/philz1337x/loras/resolve/main/more_details.safetensors?download=true](https://t.co/BrH7rtKOsJ) -> models/Lora
- [https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth?download=true](https://t.co/hKCxta2Zdr) -> models/ControlNet

4. Go to the img2img tab and apply the parameters:
Model: juggernaut_reborn,
Prompt: masterpiece, best quality, highres, <lora:more_details:0.5> <lora:SDXLrender_v2.0:1> 
Negative prompt: (worst quality, low quality, normal quality:2) JuggernautNegative-neg 
Image: The image you want to upscale
Sampler: DPM++ 3M SDE Karras,
Steps: 18,
CFG scale: 6.0,
Denoising strength: 0.35, 

Tiled Diffusion:
"Enable Tiled Diffusion": true,
"Keep input size": true,
"Method": "MultiDiffusion",
"Tile tile width": 112,
"Tile tile height": 144,
"Tile Overlap": 4,
"Tile batch size": 8,
"Upscaler": 4x-UltraSharp, 
"Scale factor": 2, 

ControlNet 0:
"Enable": true,
"Low VRAM": false,
"Pixel Perfect": true,
"Control Type": tile
"Preprocessor: tile_resample, 
"Model": control_v11f1e_sd15_tile, 
"Control weight": 0.6, 
"Starting control step": 0.0,
"Ending control step": 1.0,
"Control mode": 1,

5. Upscale:
Click Generate to upscale your image


> Free ComfyUI workflow for drag and drop -> https://github.com/philz1337x/ComfyUI-ClarityAI/blob/main/free-workflow.json

**Comment by NeverBeLazyG** [comment]
sag mal kapierst du nicht, dass dein müll so nicht funktioniert. geh mal auf einen nackten pc. und macht mal diese schritte die du da angeblich angibst. ich habe es mit deinem compfy ui workflow nochmal getestet. da kommt nur schrott bei raus wenn man damit upscaled. das hat nichts mit dem zu tun was z.b. bei magnific, leonardo oder krea ai entsteht. teste doch mal deinen schrott bevor du es veröffentlichst. man man man. so schwer kann das doch nicht sein. ich ärgere mich, dass ich so viel zeit in deinen schrott gesteckt habe. wie gesagt. schliesse den post. ich brauche es nicht mehr. habe eine andere lösung schon gefunden.

**Comment by 17Reset** [comment]
> bro sorry i dont believe you. i am in that ai upscaling and ai generation game since years, i installed like hundrets of models, workflows, compfy ui, forge, a1111, i got really everything to run. there is only one which i was not able to get run corretly, and thats yours. i think you make it intentionally, to sell your api things. its really pathetic. you take models from others, bake a little bit something new in it, and then trick around not to share the information. i read all the "issue page" information, so much people asking you for information, but all you do is to say: look readme. you dont give information.
> 
> why would you not be able to give us just one clean information, how to get this running ? this cannot be so complicated. you always give missing information. some missing link. so people are not able to get it up and running correctly.
> 
> your readme is total chaotic, you always mention to use api key. all you do is try to sell your api keys.
> 
> nor your a1111 either your comfyUI workflow works correctly.
> 
> really sad.
> 
> but meanwhile i dont care anymore, i found other upscalers, which work the same way, if not better. so use it for yourself. no one needs it anymore.

Is it convenient to share other Upscale that can be deployed locally and has good effect?

**Comment by NeverBeLazyG** [comment]
> > bro sorry i dont believe you. i am in that ai upscaling and ai generation game since years, i installed like hundrets of models, workflows, compfy ui, forge, a1111, i got really everything to run. there is only one which i was not able to get run corretly, and thats yours. i think you make it intentionally, to sell your api things. its really pathetic. you take models from others, bake a little bit something new in it, and then trick around not to share the information. i read all the "issue page" information, so much people asking you for information, but all you do is to say: look readme. you dont give information.
> > why would you not be able to give us just one clean information, how to get this running ? this cannot be so complicated. you always give missing information. some missing link. so people are not able to get it up and running correctly.
> > your readme is total chaotic, you always mention to use api key. all you do is try to sell your api keys.
> > nor your a1111 either your comfyUI workflow works correctly.
> > really sad.
> > but meanwhile i dont care anymore, i found other upscalers, which work the same way, if not better. so use it for yourself. no one needs it anymore.
> 
> Is it convenient to share other Upscale that can be deployed locally and has good effect?
After years of experience with upscaling, I have found the following: There are ultimately two main categories of upscalers. On one hand, there are creative upscalers that significantly alter the image, and on the other hand, there are those that aim to keep the overall image unchanged. The latter are characterized by preserving details such as faces and expressions, although they may be less impactful. On the other hand, there are specialized upscalers that are particularly effective with heavily low-resolution images, but their use can affect the representation of people, for example. The choice of the right upscaler strongly depends on the specific use case. If you want to enhance an image with people or portraits where the person must remain unchanged, the Supir upscaler is recommended. However, if you need an upscaler that processes extremely small source images and changes the overall image, the Clarity upscaler would be a good option. For my personal purposes, I mainly use Supir because I consider it to be the most effective upscaler I have tried so far.

**Comment by 17Reset** [comment]
> > > 兄弟，对不起，我不相信你。多年来，我一直在从事人工智能升级和人工智能生成游戏，我安装了数百个模型、工作流、compfy ui、forge、a1111，我真的可以运行一切。只有一个我无法正确运行，那就是你的。我认为你是故意这样做的，为了销售你的 api 东西。这真的很可悲。你从别人那里拿走模型，在里面加一点新东西，然后耍花招不分享信息。我读了所有的“问题页面”信息，很多人向你询问信息，但你所做的只是说：看自述文件。你不提供信息。
> > > 为什么你不能给我们一个干净的信息，如何让它运行？这不可能这么复杂。你总是提供缺失的信息。一些缺失的链接。所以人们无法正确启动和运行它。
> > > 你的自述文件完全混乱，你总是提到使用 api 密钥。你所做的就是试图出售你的 api 密钥。
> > > 您的 a1111 和 comfyUI 工作流程都无法正常工作。
> > > 真的很难过。
> > > 但与此同时我不再关心了，我发现了其他升级器，它们的工作方式相同，甚至更好。所以自己用吧。没有人再需要它了。
> > 
> > 
> > 方便分享一下其他可以本地部署，并且效果好的Upscale吗？
> 
> 经过多年的升级经验，我发现了以下几点：最终，升级器主要分为两大类。一方面，有创意的升级器可以显著改变图像，另一方面，有旨在保持整体图像不变的升级器。后者的特点是保留面部和表情等细节，尽管它们的影响可能较小。另一方面，有专门的升级器，它们对低分辨率图像特别有效，但它们的使用可能会影响人物的表现。选择合适的升级器在很大程度上取决于具体的用例。如果您想增强带有人物或肖像的图像，而人物必须保持不变，则建议使用 Supir 升级器。但是，如果您需要一个处理极小源图像并改变整体图像的升级器，Clarity 升级器将是一个不错的选择。就我个人而言，我主要使用 Supir，因为我认为它是我迄今为止尝试过的最有效的升级器。

Thanks, I tried Supir once, the picture I tested was not very good, so I gave up, but thank you very much for sharing

**Comment by 17Reset** [comment]
> > > bro sorry i dont believe you. i am in that ai upscaling and ai generation game since years, i installed like hundrets of models, workflows, compfy ui, forge, a1111, i got really everything to run. there is only one which i was not able to get run corretly, and thats yours. i think you make it intentionally, to sell your api things. its really pathetic. you take models from others, bake a little bit something new in it, and then trick around not to share the information. i read all the "issue page" information, so much people asking you for information, but all you do is to say: look readme. you dont give information.
> > > why would you not be able to give us just one clean information, how to get this running ? this cannot be so complicated. you always give missing information. some missing link. so people are not able to get it up and running correctly.
> > > your readme is total chaotic, you always mention to use api key. all you do is try to sell your api keys.
> > > nor your a1111 either your comfyUI workflow works correctly.
> > > really sad.
> > > but meanwhile i dont care anymore, i found other upscalers, which work the same way, if not better. so use it for yourself. no one needs it anymore.
> > 
> > 
> > Is it convenient to share other Upscale that can be deployed locally and has good effect?
> 
> After years of experience with upscaling, I have found the following: There are ultimately two main categories of upscalers. On one hand, there are creative upscalers that significantly alter the image, and on the other hand, there are those that aim to keep the overall image unchanged. The latter are characterized by preserving details such as faces and expressions, although they may be less impactful. On the other hand, there are specialized upscalers that are particularly effective with heavily low-resolution images, but their use can affect the representation of people, for example. The choice of the right upscaler strongly depends on the specific use case. If you want to enhance an image with people or portraits where the person must remain unchanged, the Supir upscaler is recommended. However, if you need an upscaler that processes extremely small source images and changes the overall image, the Clarity upscaler would be a good option. For my personal purposes, I mainly use Supir because I consider it to be the most effective upscaler I have tried so far.

Thanks, I tried Supir once, the picture I tested was not very good, so I gave up, but thank you very much for sharing

**Comment by NeverBeLazyG** [comment]
> > > > bro sorry i dont believe you. i am in that ai upscaling and ai generation game since years, i installed like hundrets of models, workflows, compfy ui, forge, a1111, i got really everything to run. there is only one which i was not able to get run corretly, and thats yours. i think you make it intentionally, to sell your api things. its really pathetic. you take models from others, bake a little bit something new in it, and then trick around not to share the information. i read all the "issue page" information, so much people asking you for information, but all you do is to say: look readme. you dont give information.
> > > > why would you not be able to give us just one clean information, how to get this running ? this cannot be so complicated. you always give missing information. some missing link. so people are not able to get it up and running correctly.
> > > > your readme is total chaotic, you always mention to use api key. all you do is try to sell your api keys.
> > > > nor your a1111 either your comfyUI workflow works correctly.
> > > > really sad.
> > > > but meanwhile i dont care anymore, i found other upscalers, which work the same way, if not better. so use it for yourself. no one needs it anymore.
> > > 
> > > 
> > > Is it convenient to share other Upscale that can be deployed locally and has good effect?
> > 
> > 
> > After years of experience with upscaling, I have found the following: There are ultimately two main categories of upscalers. On one hand, there are creative upscalers that significantly alter the image, and on the other hand, there are those that aim to keep the overall image unchanged. The latter are characterized by preserving details such as faces and expressions, although they may be less impactful. On the other hand, there are specialized upscalers that are particularly effective with heavily low-resolution images, but their use can affect the representation of people, for example. The choice of the right upscaler strongly depends on the specific use case. If you want to enhance an image with people or portraits where the person must remain unchanged, the Supir upscaler is recommended. However, if you need an upscaler that processes extremely small source images and changes the overall image, the Clarity upscaler would be a good option. For my personal purposes, I mainly use Supir because I consider it to be the most effective upscaler I have tried so far.
> 
> Thanks, I tried Supir once, the picture I tested was not very good, so I gave up, but thank you very much for sharing


As I already told you, Supi is only good at certain things. If you use it correctly, Supir can deliver extremely good results. Here's an example. supir is one of the best upscalers, if you use it correctly

![image](https://github.com/user-attachments/assets/9f1b867d-8c11-40dc-a19c-f47b35726753)

**Comment by rainsoulsrx** [comment]
> Please feel free to ask a constructive question; otherwise, I will close this issue.

hi, where can I set "Hr Option: HiResFixOption.BOTH"  I only can see Hires fix in text2img but not in img2img

**Comment by rainsoulsrx** [comment]
> you: "you dont give information"
> 
> meanwhile the information I gave:
> 
> How to Upscale Images for Free with Clarity Upscaler:
> 
> 1. Install A1111 WebUI (three options from hardest to easiest):
>    a) Follow the official tutorial: [https://github.com/AUTOMATIC1111/stable-diffusion-webui#installation-and-running](https://t.co/BPkc6bxYni)
>    b) Watch the YouTube tutorial: [https://youtube.com/watch?v=kqXpAKVQDNU](https://t.co/EhYZ2qnuPa)
>    c) Use One-Click start on
>    [@runpod_io](https://x.com/runpod_io)
>    :  [https://rundiffusion.com](https://t.co/79mrqzKybV) ($0.5/h)
> 2. Install the extension:
>    Open A1111 WebUl -> Click Tab "Extensions" -> Click Tab "Available" -> Find "[Tiled Diffusion with Tiled
>    VAE]" -> Click Install
> 3. Download the models and place them in the correct folder:
> 
> * [https://huggingface.co/dantea1118/juggernaut_reborn/resolve/main/juggernaut_reborn.safetensors?download=true](https://t.co/GblF3ZQI1G) -> stable-diffusion-webui/models/Stable-diffusion
> * [https://huggingface.co/philz1337x/upscaler/resolve/main/4x-UltraSharp.pth?download=true](https://t.co/sFDClKrEaN) -> models/ESRGAN
> * [https://huggingface.co/philz1337x/embeddings/resolve/main/JuggernautNegative-neg.pt?download=true](https://t.co/DSDmb35hQG) -> embeddings
> * [https://huggingface.co/philz1337x/loras/resolve/main/SDXLrender_v2.0.safetensors?download=true](https://t.co/7fLWBFVkul) -> models/Lora
> * [https://huggingface.co/philz1337x/loras/resolve/main/more_details.safetensors?download=true](https://t.co/BrH7rtKOsJ) -> models/Lora
> * [https://huggingface.co/lllyasviel/ControlNet-v1-1/resolve/main/control_v11f1e_sd15_tile.pth?download=true](https://t.co/hKCxta2Zdr) -> models/ControlNet
> 
> 4. Go to the img2img tab and apply the parameters:
>    Model: juggernaut_reborn,
>    Prompt: masterpiece, best quality, highres, lora:more_details:0.5 lora:SDXLrender_v2.0:1
>    Negative prompt: (worst quality, low quality, normal quality:2) JuggernautNegative-neg
>    Image: The image you want to upscale
>    Sampler: DPM++ 3M SDE Karras,
>    Steps: 18,
>    CFG scale: 6.0,
>    Denoising strength: 0.35,
> 
> Tiled Diffusion: "Enable Tiled Diffusion": true, "Keep input size": true, "Method": "MultiDiffusion", "Tile tile width": 112, "Tile tile height": 144, "Tile Overlap": 4, "Tile batch size": 8, "Upscaler": 4x-UltraSharp, "Scale factor": 2,
> 
> ControlNet 0: "Enable": true, "Low VRAM": false, "Pixel Perfect": true, "Control Type": tile "Preprocessor: tile_resample, "Model": control_v11f1e_sd15_tile, "Control weight": 0.6, "Starting control step": 0.0, "Ending control step": 1.0, "Control mode": 1,
> 
> 5. Upscale:
>    Click Generate to upscale your image

Could you provide a screenshot of the parameter settings? just like this https://private-user-images.githubusercontent.com/64243335/318007325-00fa457b-2d4f-411b-a730-ecf0c4339dba.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY3NjM2MDMsIm5iZiI6MTczNjc2MzMwMywicGF0aCI6Ii82NDI0MzMzNS8zMTgwMDczMjUtMDBmYTQ1N2ItMmQ0Zi00MTFiLWE3MzAtZWNmMGM0MzM5ZGJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMTMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTEzVDEwMTUwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmNGRlNGYxMmRjMTExNzAxMTM0YTU2ODdiYzg0MDNkMjMzNTc3ZjVkMGU5OTZjM2JmNzZiODk3ODMxNjk0YTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.iZVSm_HTyunvxaEwZMveWZDFhDSBGVPZRvsaMVG9HRQ
