### ISSUE TITLE
How to run on personal computer?

### ISSUE THREAD

**Issue by aravindhv10** [philz1337x/clarity-upscaler#9]
Hi, I am trying to run this but all I get is an automatic1111 screen. There seems to be no instructions on how to run the upscaler.
Can you include the exact steps or provide a simple python script for this?

**Comment by philz1337x** [comment]
This repo is a cog implementation. If you are not familiar with cog, please use a1111 instead: https://github.com/philz1337x/clarity-upscaler?tab=readme-ov-file#run-with-a1111-webui
